# -*- coding: utf-8 -*-
"""Drill-down (item_action) configuration for service_dashboards_ct.

Auto-generated from the JSON exports under
``20260617_DrillDown_ListIView_Fixed/``. Re-generate with:

    python3 scripts/gen_drill_actions.py

Schema: ``DRILL_ACTIONS[<board name>][<item name>]`` is an ordered list
of action dicts; each dict carries the model + field name + chart type
used at that drill level. ``hooks.apply_drill_actions(env)`` materialises
the actual ``ks_dashboard_ninja.item_action`` rows from this mapping.
"""

DRILL_ACTIONS = {   'Sales & Cost Analysis - New': {   'Labour Revenue - Region Wise': [   {   'chart_type': 'ks_bar_chart',
                                                                               'date_groupby': False,
                                                                               'field': 'work_center_id',
                                                                               'model': 'dbmodel.jobcards.analysis.ct',
                                                                               'record_limit': 0,
                                                                               'sequence': 0}],
                                       'Labour Revenue - Region Wise (%)': [   {   'chart_type': 'ks_bar_chart',
                                                                                   'date_groupby': False,
                                                                                   'field': 'work_center_id',
                                                                                   'model': 'dbmodel.jobcards.analysis.ct',
                                                                                   'record_limit': 0,
                                                                                   'sequence': 0}],
                                       'Spare Parts Revenue - Region Wise': [   {   'chart_type': 'ks_bar_chart',
                                                                                    'date_groupby': False,
                                                                                    'field': 'work_center_id',
                                                                                    'model': 'dbmodel.jobcards.analysis.ct',
                                                                                    'record_limit': 0,
                                                                                    'sequence': 0}],
                                       'Spare Parts Revenue - Region Wise (%)': [   {   'chart_type': 'ks_bar_chart',
                                                                                        'date_groupby': False,
                                                                                        'field': 'work_center_id',
                                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                                        'record_limit': 0,
                                                                                        'sequence': 0}],
                                       'Spare Parts Warranty Revenue - Region Wise': [   {   'chart_type': 'ks_bar_chart',
                                                                                             'date_groupby': False,
                                                                                             'field': 'work_center_id',
                                                                                             'model': 'dbmodel.jobcards.analysis.ct',
                                                                                             'record_limit': 0,
                                                                                             'sequence': 0}],
                                       'Total Service Revenue - Month Wise': [   {   'chart_type': 'ks_bar_chart',
                                                                                     'date_groupby': False,
                                                                                     'field': 'work_center_id',
                                                                                     'model': 'dbmodel.jobcards.analysis.ct',
                                                                                     'record_limit': 0,
                                                                                     'sequence': 0}],
                                       'Total Service Revenue - Month Wise (%)': [   {   'chart_type': 'ks_bar_chart',
                                                                                         'date_groupby': False,
                                                                                         'field': 'work_center_id',
                                                                                         'model': 'dbmodel.jobcards.analysis.ct',
                                                                                         'record_limit': 0,
                                                                                         'sequence': 0}],
                                       'Total Service Revenue - Region Wise': [   {   'chart_type': 'ks_bar_chart',
                                                                                      'date_groupby': False,
                                                                                      'field': 'work_center_id',
                                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                                      'record_limit': 0,
                                                                                      'sequence': 0}],
                                       'Total Service Revenue - Region Wise (%)': [   {   'chart_type': 'ks_bar_chart',
                                                                                          'date_groupby': False,
                                                                                          'field': 'work_center_id',
                                                                                          'model': 'dbmodel.jobcards.analysis.ct',
                                                                                          'record_limit': 0,
                                                                                          'sequence': 0}]},
    'Service Analysis (C) - New': {   'Job Cards - Month Wise': [   {   'chart_type': 'ks_bar_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'work_center_id',
                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 0}],
                                      'Job Cards - Not Closed Status analysis on weekly basis': [   {   'chart_type': 'ks_bar_chart',
                                                                                                        'date_groupby': False,
                                                                                                        'field': 'work_center_id',
                                                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                        'record_limit': 0,
                                                                                                        'sequence': 2}],
                                      'Job Cards - Status Wise (Closed & Cancelled)': [   {   'chart_type': 'ks_bar_chart',
                                                                                              'date_groupby': False,
                                                                                              'field': 'work_center_id',
                                                                                              'model': 'dbmodel.jobcards.analysis.ct',
                                                                                              'record_limit': 0,
                                                                                              'sequence': 0}],
                                      'Job Cards - Status Wise (Except Closed & Cancelled)': [   {   'chart_type': 'ks_bar_chart',
                                                                                                     'date_groupby': False,
                                                                                                     'field': 'work_center_id',
                                                                                                     'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                     'record_limit': 0,
                                                                                                     'sequence': 0}],
                                      'Job Cards - Status analysis on weekly basis': [   {   'chart_type': 'ks_bar_chart',
                                                                                             'date_groupby': False,
                                                                                             'field': 'action_status',
                                                                                             'model': 'dbmodel.jobcards.analysis.ct',
                                                                                             'record_limit': 0,
                                                                                             'sequence': 0},
                                                                                         {   'chart_type': 'ks_bar_chart',
                                                                                             'date_groupby': False,
                                                                                             'field': 'work_center_id',
                                                                                             'model': 'dbmodel.jobcards.analysis.ct',
                                                                                             'record_limit': 0,
                                                                                             'sequence': 1}],
                                      'Job Cards - Warranty Status Wise (%)': [   {   'chart_type': 'ks_pie_chart',
                                                                                      'date_groupby': False,
                                                                                      'field': 'work_center_group_id',
                                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                                      'record_limit': 0,
                                                                                      'sequence': 0},
                                                                                  {   'chart_type': 'ks_pie_chart',
                                                                                      'date_groupby': False,
                                                                                      'field': 'work_center_id',
                                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                                      'record_limit': 0,
                                                                                      'sequence': 1}],
                                      'Warranty Sts & Region - Jobs Count': [   {   'chart_type': 'ks_bar_chart',
                                                                                    'date_groupby': False,
                                                                                    'field': 'work_center_group_id',
                                                                                    'model': 'dbmodel.jobcards.analysis.ct',
                                                                                    'record_limit': 0,
                                                                                    'sequence': 0},
                                                                                {   'chart_type': 'ks_bar_chart',
                                                                                    'date_groupby': False,
                                                                                    'field': 'work_center_id',
                                                                                    'model': 'dbmodel.jobcards.analysis.ct',
                                                                                    'record_limit': 0,
                                                                                    'sequence': 1}]},
    'Service Analysis (CC) - New': {   'Total Job Cards - Month wise': [   {   'chart_type': 'ks_bar_chart',
                                                                               'date_groupby': False,
                                                                               'field': 'work_center_group_id',
                                                                               'model': 'dbmodel.usergroup.analysis.ct',
                                                                               'record_limit': 0,
                                                                               'sequence': 0}],
                                       'Total Job Cards - User wise': [   {   'chart_type': 'ks_bar_chart',
                                                                              'date_groupby': False,
                                                                              'field': 'work_center_group_id',
                                                                              'model': 'dbmodel.usergroup.analysis.ct',
                                                                              'record_limit': 0,
                                                                              'sequence': 0}]},
    'Service Analysis (CRD) - New': {   'Job Cards - Users wise': [   {   'chart_type': 'ks_bar_chart',
                                                                          'date_groupby': False,
                                                                          'field': 'region',
                                                                          'model': 'dbmodel.task.message.log.analysis.ct',
                                                                          'record_limit': 0,
                                                                          'sequence': 0},
                                                                      {   'chart_type': 'ks_bar_chart',
                                                                          'date_groupby': False,
                                                                          'field': 'city',
                                                                          'model': 'dbmodel.task.message.log.analysis.ct',
                                                                          'record_limit': 0,
                                                                          'sequence': 1}],
                                        'Total Closed Job Cards - Month wise': [   {   'chart_type': 'ks_bar_chart',
                                                                                       'date_groupby': False,
                                                                                       'field': 'work_center_id',
                                                                                       'model': 'dbmodel.jobcards.analysis.ct',
                                                                                       'record_limit': 0,
                                                                                       'sequence': 0}],
                                        'Total Scheduled Job Cards - Month wise': [   {   'chart_type': 'ks_bar_chart',
                                                                                          'date_groupby': False,
                                                                                          'field': 'work_center_id',
                                                                                          'model': 'dbmodel.jobcards.analysis.ct',
                                                                                          'record_limit': 0,
                                                                                          'sequence': 0}]},
    'Service Analysis (E) - New': {   'Job Cards - Month Wise': [   {   'chart_type': 'ks_bar_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'work_center_id',
                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 0}],
                                      'Job Cards - Not Closed Status analysis on weekly basis': [   {   'chart_type': 'ks_bar_chart',
                                                                                                        'date_groupby': False,
                                                                                                        'field': 'work_center_id',
                                                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                        'record_limit': 0,
                                                                                                        'sequence': 2}],
                                      'Job Cards - Status Wise (Closed & Cancelled)': [   {   'chart_type': 'ks_bar_chart',
                                                                                              'date_groupby': False,
                                                                                              'field': 'work_center_id',
                                                                                              'model': 'dbmodel.jobcards.analysis.ct',
                                                                                              'record_limit': 0,
                                                                                              'sequence': 0}],
                                      'Job Cards - Status Wise (Except Closed & Cancelled)': [   {   'chart_type': 'ks_bar_chart',
                                                                                                     'date_groupby': False,
                                                                                                     'field': 'work_center_id',
                                                                                                     'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                     'record_limit': 0,
                                                                                                     'sequence': 0}],
                                      'Job Cards - Status analysis on weekly basis': [   {   'chart_type': 'ks_bar_chart',
                                                                                             'date_groupby': False,
                                                                                             'field': 'action_status',
                                                                                             'model': 'dbmodel.jobcards.analysis.ct',
                                                                                             'record_limit': 0,
                                                                                             'sequence': 0},
                                                                                         {   'chart_type': 'ks_bar_chart',
                                                                                             'date_groupby': False,
                                                                                             'field': 'work_center_id',
                                                                                             'model': 'dbmodel.jobcards.analysis.ct',
                                                                                             'record_limit': 0,
                                                                                             'sequence': 1}],
                                      'Job Cards - Warranty Status Wise (%)': [   {   'chart_type': 'ks_pie_chart',
                                                                                      'date_groupby': False,
                                                                                      'field': 'work_center_group_id',
                                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                                      'record_limit': 0,
                                                                                      'sequence': 0},
                                                                                  {   'chart_type': 'ks_pie_chart',
                                                                                      'date_groupby': False,
                                                                                      'field': 'work_center_id',
                                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                                      'record_limit': 0,
                                                                                      'sequence': 1}],
                                      'Warranty Sts & Region - Jobs Count': [   {   'chart_type': 'ks_bar_chart',
                                                                                    'date_groupby': False,
                                                                                    'field': 'work_center_group_id',
                                                                                    'model': 'dbmodel.jobcards.analysis.ct',
                                                                                    'record_limit': 0,
                                                                                    'sequence': 0},
                                                                                {   'chart_type': 'ks_bar_chart',
                                                                                    'date_groupby': False,
                                                                                    'field': 'work_center_id',
                                                                                    'model': 'dbmodel.jobcards.analysis.ct',
                                                                                    'record_limit': 0,
                                                                                    'sequence': 1}]},
    'Service Analysis (JCs) - New': {   'Job Cards - Status analysis on weekly basis': [   {   'chart_type': 'ks_bar_chart',
                                                                                               'date_groupby': False,
                                                                                               'field': 'work_center_group_id',
                                                                                               'model': 'dbmodel.jobcards.analysis.ct',
                                                                                               'record_limit': 0,
                                                                                               'sequence': 0}]},
    'Service Analysis (Parts) - New': {   'Job Card - Status wise Analysis': [   {   'chart_type': 'ks_bar_chart',
                                                                                     'date_groupby': False,
                                                                                     'field': 'work_center_group_id',
                                                                                     'model': 'dbmodel.jobcards.analysis.ct',
                                                                                     'record_limit': 0,
                                                                                     'sequence': 0},
                                                                                 {   'chart_type': 'ks_bar_chart',
                                                                                     'date_groupby': False,
                                                                                     'field': 'work_center_id',
                                                                                     'model': 'dbmodel.jobcards.analysis.ct',
                                                                                     'record_limit': 0,
                                                                                     'sequence': 1}],
                                          'Job Card - User wise Analysis': [   {   'chart_type': 'ks_bar_chart',
                                                                                   'date_groupby': False,
                                                                                   'field': 'city',
                                                                                   'model': 'dbmodel.task.message.log.analysis.ct',
                                                                                   'record_limit': 0,
                                                                                   'sequence': 1}],
                                          'Waiting period from On hold to parts ready state': [   {   'chart_type': 'ks_bar_chart',
                                                                                                      'date_groupby': False,
                                                                                                      'field': 'work_center_id',
                                                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                      'record_limit': 0,
                                                                                                      'sequence': 0}],
                                          'Waiting period from quotation to parts ready state': [   {   'chart_type': 'ks_bar_chart',
                                                                                                        'date_groupby': False,
                                                                                                        'field': 'work_center_id',
                                                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                        'record_limit': 0,
                                                                                                        'sequence': 0}]},
    'Service Analysis (UWC) - New': {   'Job Cards - Default Work Centre Wise': [   {   'chart_type': 'ks_bar_chart',
                                                                                        'date_groupby': False,
                                                                                        'field': 'work_center_group_id',
                                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                                        'record_limit': 0,
                                                                                        'sequence': 0}],
                                        'Job Cards - Month Wise': [   {   'chart_type': 'ks_bar_chart',
                                                                          'date_groupby': False,
                                                                          'field': 'work_center_id',
                                                                          'model': 'dbmodel.jobcards.analysis.ct',
                                                                          'record_limit': 0,
                                                                          'sequence': 0}],
                                        'Job Cards - Status Wise (Closed & Cancelled)': [   {   'chart_type': 'ks_pie_chart',
                                                                                                'date_groupby': False,
                                                                                                'field': 'work_center_id',
                                                                                                'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                'record_limit': 0,
                                                                                                'sequence': 0}],
                                        'Job Cards - Status Wise (Except Closed & Cancelled)': [   {   'chart_type': 'ks_bar_chart',
                                                                                                       'date_groupby': False,
                                                                                                       'field': 'work_center_id',
                                                                                                       'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                       'record_limit': 0,
                                                                                                       'sequence': 0}],
                                        'Job Cards - Status analysis on weekly basis': [   {   'chart_type': 'ks_bar_chart',
                                                                                               'date_groupby': False,
                                                                                               'field': 'action_status',
                                                                                               'model': 'dbmodel.jobcards.analysis.ct',
                                                                                               'record_limit': 0,
                                                                                               'sequence': 0},
                                                                                           {   'chart_type': 'ks_bar_chart',
                                                                                               'date_groupby': False,
                                                                                               'field': 'work_center_id',
                                                                                               'model': 'dbmodel.jobcards.analysis.ct',
                                                                                               'record_limit': 0,
                                                                                               'sequence': 1}],
                                        'Job Cards - Warranty Wise (%)': [   {   'chart_type': 'ks_pie_chart',
                                                                                 'date_groupby': False,
                                                                                 'field': 'work_center_group_id',
                                                                                 'model': 'dbmodel.jobcards.analysis.ct',
                                                                                 'record_limit': 0,
                                                                                 'sequence': 0},
                                                                             {   'chart_type': 'ks_pie_chart',
                                                                                 'date_groupby': False,
                                                                                 'field': 'work_center_id',
                                                                                 'model': 'dbmodel.jobcards.analysis.ct',
                                                                                 'record_limit': 0,
                                                                                 'sequence': 1}],
                                        'Warranty Sts & Region - Jobs Count': [   {   'chart_type': 'ks_bar_chart',
                                                                                      'date_groupby': False,
                                                                                      'field': 'work_center_id',
                                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                                      'record_limit': 0,
                                                                                      'sequence': 0},
                                                                                  {   'chart_type': 'ks_bar_chart',
                                                                                      'date_groupby': False,
                                                                                      'field': 'work_center_group_id',
                                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                                      'record_limit': 0,
                                                                                      'sequence': 1}]},
    'Service Analysis (W) - New': {   'Job Cards - Month Wise': [   {   'chart_type': 'ks_bar_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'work_center_id',
                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 0}],
                                      'Job Cards - Not Closed Status analysis on weekly basis': [   {   'chart_type': 'ks_bar_chart',
                                                                                                        'date_groupby': False,
                                                                                                        'field': 'work_center_id',
                                                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                        'record_limit': 0,
                                                                                                        'sequence': 2}],
                                      'Job Cards - Status Wise (Closed & Cancelled)': [   {   'chart_type': 'ks_bar_chart',
                                                                                              'date_groupby': False,
                                                                                              'field': 'work_center_id',
                                                                                              'model': 'dbmodel.jobcards.analysis.ct',
                                                                                              'record_limit': 0,
                                                                                              'sequence': 0}],
                                      'Job Cards - Status Wise (Except Closed & Cancelled)': [   {   'chart_type': 'ks_bar_chart',
                                                                                                     'date_groupby': False,
                                                                                                     'field': 'work_center_id',
                                                                                                     'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                     'record_limit': 0,
                                                                                                     'sequence': 0}],
                                      'Job Cards - Status analysis on weekly basis': [   {   'chart_type': 'ks_bar_chart',
                                                                                             'date_groupby': False,
                                                                                             'field': 'action_status',
                                                                                             'model': 'dbmodel.jobcards.analysis.ct',
                                                                                             'record_limit': 0,
                                                                                             'sequence': 1},
                                                                                         {   'chart_type': 'ks_bar_chart',
                                                                                             'date_groupby': False,
                                                                                             'field': 'work_center_id',
                                                                                             'model': 'dbmodel.jobcards.analysis.ct',
                                                                                             'record_limit': 0,
                                                                                             'sequence': 2}],
                                      'Job Cards - Warranty Status Wise (%)': [   {   'chart_type': 'ks_pie_chart',
                                                                                      'date_groupby': False,
                                                                                      'field': 'work_center_group_id',
                                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                                      'record_limit': 0,
                                                                                      'sequence': 0},
                                                                                  {   'chart_type': 'ks_pie_chart',
                                                                                      'date_groupby': False,
                                                                                      'field': 'work_center_id',
                                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                                      'record_limit': 0,
                                                                                      'sequence': 1}],
                                      'Warranty Sts & Region - Jobs Count': [   {   'chart_type': 'ks_bar_chart',
                                                                                    'date_groupby': False,
                                                                                    'field': 'work_center_group_id',
                                                                                    'model': 'dbmodel.jobcards.analysis.ct',
                                                                                    'record_limit': 0,
                                                                                    'sequence': 0},
                                                                                {   'chart_type': 'ks_bar_chart',
                                                                                    'date_groupby': False,
                                                                                    'field': 'work_center_id',
                                                                                    'model': 'dbmodel.jobcards.analysis.ct',
                                                                                    'record_limit': 0,
                                                                                    'sequence': 1}]},
    'Service Analysis - CC Users': {   'Tasks - Month wise': [   {   'chart_type': 'ks_bar_chart',
                                                                     'date_groupby': False,
                                                                     'field': 'ptml_final_taskstatus',
                                                                     'model': 'dbmodel.task.message.log.analysis.ct',
                                                                     'record_limit': 0,
                                                                     'sequence': 0},
                                                                 {   'chart_type': 'ks_bar_chart',
                                                                     'date_groupby': False,
                                                                     'field': 'city',
                                                                     'model': 'dbmodel.task.message.log.analysis.ct',
                                                                     'record_limit': 0,
                                                                     'sequence': 1}]},
    'Service Analysis - CRD Users': {   'Tasks - Month wise': [   {   'chart_type': 'ks_bar_chart',
                                                                      'date_groupby': False,
                                                                      'field': 'ptml_final_taskstatus',
                                                                      'model': 'dbmodel.task.message.log.analysis.ct',
                                                                      'record_limit': 0,
                                                                      'sequence': 0},
                                                                  {   'chart_type': 'ks_bar_chart',
                                                                      'date_groupby': False,
                                                                      'field': 'city',
                                                                      'model': 'dbmodel.task.message.log.analysis.ct',
                                                                      'record_limit': 0,
                                                                      'sequence': 1}],
                                        'Tasks - User Role wise': [   {   'chart_type': 'ks_bar_chart',
                                                                          'date_groupby': False,
                                                                          'field': 'user_name',
                                                                          'model': 'dbmodel.task.message.log.analysis.ct',
                                                                          'record_limit': 0,
                                                                          'sequence': 0},
                                                                      {   'chart_type': 'ks_bar_chart',
                                                                          'date_groupby': False,
                                                                          'field': 'status_transition',
                                                                          'model': 'dbmodel.task.message.log.analysis.ct',
                                                                          'record_limit': 0,
                                                                          'sequence': 2}]},
    'Service Analysis - New': {   'Employee Performance Analysis - Actual Hours': [   {   'chart_type': 'ks_bar_chart',
                                                                                          'date_groupby': False,
                                                                                          'field': 'work_center_id',
                                                                                          'model': 'dbmodel.jobcards.analysis.ct',
                                                                                          'record_limit': 0,
                                                                                          'sequence': 0},
                                                                                      {   'chart_type': 'ks_bar_chart',
                                                                                          'date_groupby': False,
                                                                                          'field': 'technician_id',
                                                                                          'model': 'dbmodel.jobcards.analysis.ct',
                                                                                          'record_limit': 0,
                                                                                          'sequence': 1}],
                                  'Job Cards - Not Closed Status analysis on weekly basis': [   {   'chart_type': 'ks_bar_chart',
                                                                                                    'date_groupby': False,
                                                                                                    'field': 'work_center_id',
                                                                                                    'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                    'record_limit': 0,
                                                                                                    'sequence': 2}],
                                  'Job Cards - Status analysis on weekly basis': [   {   'chart_type': 'ks_bar_chart',
                                                                                         'date_groupby': False,
                                                                                         'field': 'action_status',
                                                                                         'model': 'dbmodel.jobcards.analysis.ct',
                                                                                         'record_limit': 0,
                                                                                         'sequence': 1},
                                                                                     {   'chart_type': 'ks_bar_chart',
                                                                                         'date_groupby': False,
                                                                                         'field': 'work_center_id',
                                                                                         'model': 'dbmodel.jobcards.analysis.ct',
                                                                                         'record_limit': 0,
                                                                                         'sequence': 2}],
                                  'Job Status Wise - Count': [   {   'chart_type': 'ks_bar_chart',
                                                                     'date_groupby': False,
                                                                     'field': 'work_center_id',
                                                                     'model': 'dbmodel.jobcards.analysis.ct',
                                                                     'record_limit': 0,
                                                                     'sequence': 0},
                                                                 {   'chart_type': 'ks_bar_chart',
                                                                     'date_groupby': False,
                                                                     'field': 'work_center_id',
                                                                     'model': 'dbmodel.jobcards.analysis.ct',
                                                                     'record_limit': 0,
                                                                     'sequence': 0}],
                                  'Month wise - Jobs Count': [   {   'chart_type': 'ks_bar_chart',
                                                                     'date_groupby': False,
                                                                     'field': 'work_center_id',
                                                                     'model': 'dbmodel.jobcards.analysis.ct',
                                                                     'record_limit': 0,
                                                                     'sequence': 0}],
                                  'Region Wise - Jobs (%)': [   {   'chart_type': 'ks_pie_chart',
                                                                    'date_groupby': False,
                                                                    'field': 'work_center_id',
                                                                    'model': 'dbmodel.jobcards.analysis.ct',
                                                                    'record_limit': 0,
                                                                    'sequence': 0}],
                                  'Region Wise - Jobs Count': [   {   'chart_type': 'ks_bar_chart',
                                                                      'date_groupby': False,
                                                                      'field': 'work_center_id',
                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                      'record_limit': 0,
                                                                      'sequence': 0}],
                                  'Region Wise - RTAT (Avg %)': [   {   'chart_type': 'ks_pie_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'work_center_id',
                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 0}],
                                  'Region Wise - RTAT (Avg)': [   {   'chart_type': 'ks_bar_chart',
                                                                      'date_groupby': False,
                                                                      'field': 'work_center_id',
                                                                      'model': 'dbmodel.jobcards.analysis.ct',
                                                                      'record_limit': 0,
                                                                      'sequence': 0}],
                                  'Warranty Status - Jobs (%)': [   {   'chart_type': 'ks_pie_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'work_center_group_id',
                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 0},
                                                                    {   'chart_type': 'ks_pie_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'work_center_id',
                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 1}],
                                  'Warranty Sts & Region - Jobs Count': [   {   'chart_type': 'ks_bar_chart',
                                                                                'date_groupby': False,
                                                                                'field': 'work_center_group_id',
                                                                                'model': 'dbmodel.jobcards.analysis.ct',
                                                                                'record_limit': 0,
                                                                                'sequence': 0},
                                                                            {   'chart_type': 'ks_bar_chart',
                                                                                'date_groupby': False,
                                                                                'field': 'work_center_id',
                                                                                'model': 'dbmodel.jobcards.analysis.ct',
                                                                                'record_limit': 0,
                                                                                'sequence': 1}]},
    'Service Analysis - Parts Users': {   'Customer Need Quote Hours': [   {   'chart_type': 'ks_bar_chart',
                                                                               'date_groupby': False,
                                                                               'field': 'work_center_id',
                                                                               'model': 'dbmodel.jobcards.analysis.ct',
                                                                               'record_limit': 0,
                                                                               'sequence': 0}],
                                          'On Hold -SP Req Hours': [   {   'chart_type': 'ks_bar_chart',
                                                                           'date_groupby': False,
                                                                           'field': 'work_center_id',
                                                                           'model': 'dbmodel.jobcards.analysis.ct',
                                                                           'record_limit': 0,
                                                                           'sequence': 0}],
                                          'Tasks - Month wise': [   {   'chart_type': 'ks_bar_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'work_center_group_id',
                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 0},
                                                                    {   'chart_type': 'ks_bar_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'work_center_id',
                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 1}]},
    'Service Analysis - Technicians': {   'Tasks - Month wise': [   {   'chart_type': 'ks_bar_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'ptml_final_taskstatus',
                                                                        'model': 'dbmodel.task.message.log.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 0},
                                                                    {   'chart_type': 'ks_bar_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'city',
                                                                        'model': 'dbmodel.task.message.log.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 1}],
                                          'Technician Travel Hours': [   {   'chart_type': 'ks_bar_chart',
                                                                             'date_groupby': False,
                                                                             'field': 'work_center_id',
                                                                             'model': 'dbmodel.jobcards.analysis.ct',
                                                                             'record_limit': 0,
                                                                             'sequence': 0}]},
    'Technician Analysis - New': {   'Employee Performance Analysis - Estimated vs Actual Hours': [   {   'chart_type': 'ks_bar_chart',
                                                                                                          'date_groupby': False,
                                                                                                          'field': 'work_center_id',
                                                                                                          'model': 'dbmodel.jobcards.analysis.ct',
                                                                                                          'record_limit': 0,
                                                                                                          'sequence': 0}],
                                     'Technician Jobs': [   {   'chart_type': 'ks_bar_chart',
                                                                'date_groupby': False,
                                                                'field': 'work_center_id',
                                                                'model': 'dbmodel.jobcards.analysis.ct',
                                                                'record_limit': 0,
                                                                'sequence': 0}],
                                     'Technician Jobs - RTAT AVG': [   {   'chart_type': 'ks_bar_chart',
                                                                           'date_groupby': False,
                                                                           'field': 'work_center_id',
                                                                           'model': 'dbmodel.jobcards.analysis.ct',
                                                                           'record_limit': 0,
                                                                           'sequence': 0}],
                                     'Technician Travel Hours': [   {   'chart_type': 'ks_bar_chart',
                                                                        'date_groupby': False,
                                                                        'field': 'work_center_id',
                                                                        'model': 'dbmodel.jobcards.analysis.ct',
                                                                        'record_limit': 0,
                                                                        'sequence': 0}]}}
