from odoo import models, fields, api

class ResLangCustom(models.Model):
    _name = 'customer'
    _description = 'customer Model'

    cst_account = fields.Char(string='cst_account')
    cst_add = fields.Char(string='cst_add')
    cst_add2 = fields.Char(string='cst_add2')
    cst_addno = fields.Char(string='cst_addno')
    cst_alloweditcstname = fields.Char(string='cst_alloweditcstname')
    cst_allowloyalty = fields.Char(string='cst_allowloyalty')
    cst_balance = fields.Char(string='cst_balance')
    cst_buildno = fields.Char(string='cst_buildno')
    cst_calcretailfromfix = fields.Char(string='cst_calcretailfromfix')
    cst_climit = fields.Char(string='cst_climit')
    cst_cname = fields.Char(string='cst_cname')
    cst_cname2 = fields.Char(string='cst_cname2')
    cst_comreg = fields.Char(string='cst_comreg')
    cst_credit = fields.Char(string='cst_credit')
    cst_cstclassification = fields.Char(string='cst_cstclassification')
    cst_cstpromogrp = fields.Char(string='cst_cstpromogrp')
    cst_ctitle = fields.Char(string='cst_ctitle')
    cst_ctitle2 = fields.Char(string='cst_ctitle2')
    cst_defslt = fields.Char(string='cst_defslt')
    cst_defwh = fields.Char(string='cst_defwh')
    cst_disabled = fields.Char(string='cst_disabled')
    cst_district = fields.Char(string='cst_district')
    cst_doctype = fields.Char(string='cst_doctype')
    cst_dsireq = fields.Char(string='cst_dsireq')
    cst_email = fields.Char(string='cst_email')
    cst_export = fields.Char(string='cst_export')
    cst_exsh = fields.Char(string='cst_exsh')
    cst_fax = fields.Char(string='cst_fax')
    cst_hhscash = fields.Char(string='cst_hhscash')
    cst_idnumber = fields.Char(string='cst_idnumber')
    cst_intdate = fields.Char(string='cst_intdate')
    cst_invreqautocrnote = fields.Char(string='cst_invreqautocrnote')
    cst_lpoint = fields.Char(string='cst_lpoint')
    cst_lredeem = fields.Char(string='cst_lredeem')
    cst_message = fields.Char(string='cst_message')
    cst_message2 = fields.Char(string='cst_message2')
    cst_name = fields.Char(string='cst_name')
    cst_name2 = fields.Char(string='cst_name2')
    cst_nationality = fields.Char(string='cst_nationality')
    cst_nearby = fields.Char(string='cst_nearby')
    cst_no = fields.Char(string='cst_no')
    cst_noofvehicles = fields.Char(string='cst_noofvehicles')
    cst_odsi = fields.Char(string='cst_odsi')
    cst_otheradd = fields.Char(string='cst_otheradd')
    cst_partcustomer = fields.Char(string='cst_partcustomer')
    cst_pcode = fields.Char(string='cst_pcode')
    cst_region = fields.Char(string='cst_region')
    cst_showdiscount = fields.Char(string='cst_showdiscount')
    cst_sman = fields.Char(string='cst_sman')
    cst_streetname = fields.Char(string='cst_streetname')
    cst_subregion = fields.Char(string='cst_subregion')
    cst_suspendc = fields.Char(string='cst_suspendc')
    cst_tele = fields.Char(string='cst_tele')
    cst_tprv = fields.Char(string='cst_tprv')
    cst_ty1 = fields.Char(string='cst_ty1')
    cst_ty2 = fields.Char(string='cst_ty2')
    cst_ty3 = fields.Char(string='cst_ty3')
    cst_ty4 = fields.Char(string='cst_ty4')
    cst_vatgrp = fields.Char(string='cst_vatgrp')
    cst_vatreg = fields.Char(string='cst_vatreg')
    cst_whcrcustomer = fields.Char(string='cst_whcrcustomer')
    cst_ytd = fields.Char(string='cst_ytd')
    lang_flag = fields.Char(string='lang_flag')
    lang_flag2 = fields.Char(string='lang_flag2')
    user_id = fields.Char(string='user_id')
    user_lmd = fields.Char(string='user_lmd')


