import base64
import logging
from odoo import models, fields, api, _
from odoo.exceptions import UserError
from io import BytesIO
import datetime
try:
    import pandas as pd
except ImportError:
    pd = None

_logger = logging.getLogger(__name__)


class MaintenanceEquipmentImportWizard(models.TransientModel):
    _name = 'maintenance.equipment.import.wizard'
    _description = 'Import Maintenance Equipment from Excel'

    contract_id = fields.Many2one('subscription.contracts', string="Contract ID", required=False)
    customer_id = fields.Many2one('res.partner', string="Customer")
    description = fields.Char(string="Description")
    contract_start_date = fields.Date(string="Contract Start Date")
    contract_end_date = fields.Date(string="Contract End Date")

    file = fields.Binary(string="Excel File")
    filename = fields.Char(string="Filename")

    # ---------------------------
    # ONCHANGE
    # ---------------------------
    @api.onchange('contract_id')
    def _onchange_contract_id(self):
        for rec in self:
            rec.description = rec.contract_id.reference or False
            rec.customer_id = rec.contract_id.partner_id.id or False
            rec.contract_start_date = rec.contract_id.date_start or False
            rec.contract_end_date = rec.contract_id.date_end or False

    def action_download_template(self, **kwargs):
        # Contract can come from self or kwargs
        contract_id = self.contract_id.id if self and self.contract_id else kwargs.get('contract_id')
        if not contract_id:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': 'Warning',
                    'message': 'Please select a Contract first',
                    'type': 'warning',
                }
            }

        return {
            'type': 'ir.actions.act_url',
            'url': f'/hhs/download/equipment/template?contract_id={contract_id}',
            'target': 'self',
        }

    # ---------------------------
    # HELPERS
    # ---------------------------
    def normalize(self, col):
        return (
            str(col).strip()
            .lower()
            .replace('\n', ' ')
            .replace('(', '')
            .replace(')', '')
            .replace('-', ' ')
            .replace('__', '_')
            .replace('  ', ' ')
            .replace(' ', '_')
        )

    def get_col(self, col_map, *possible_names):
        for key in col_map:
            key_clean = key.replace('_', '')
            for name in possible_names:
                name_clean = name.replace('_', '')
                if name_clean in key_clean:
                    return col_map[key]
        return None

    def get_val(self, row, headers, key):
        col = headers.get(key)
        return str(row.get(col, '')).strip() if col else ''

    # ---------------------------
    # MAIN IMPORT
    # ---------------------------
    def action_import_equipment(self):
        self.ensure_one()
    
        if not self.file:
            raise UserError(_("Please select an Excel file."))
    
        if not pd:
            raise UserError(_("pandas is required. Install with: pip install pandas openpyxl"))
    
        try:
            file_content = base64.b64decode(self.file)
    
            # ---------------------------
            # READ FILE
            # ---------------------------
            df = pd.read_excel(BytesIO(file_content), dtype=str, header=None)
            df = df.fillna('')
    
            # ---------------------------
            # DETECT HEADER
            # ---------------------------
            header_row_index = None
            for i in range(min(10, len(df))):
                row_values = df.iloc[i].astype(str).str.lower().tolist()
                if any('serial' in val for val in row_values):
                    header_row_index = i
                    break
    
            if header_row_index is None:
                raise UserError("Header row not found. 'Serial No' column missing.")
    
            df.columns = df.iloc[header_row_index]
            df = df[header_row_index + 1:]
    
            # ---------------------------
            # COLUMN MAP
            # ---------------------------
            col_map = {self.normalize(col): col for col in df.columns}
    
            headers = {
                'asset_tag': self.get_col(col_map, 'assettagautogenerated', 'assettag'),
                'unit_type': self.get_col(col_map, 'unittype'),
                'serial_no': self.get_col(col_map, 'serialnooptional', 'serialno'),
                'model': self.get_col(col_map, 'model'),
                'brand': self.get_col(col_map, 'brand'),
                'location': self.get_col(col_map, 'usedinlocationoptional', 'location'),
                'batch_no': self.get_col(col_map, 'batchnooptional', 'batchno'),
                'no_of_visits_per_year': self.get_col(col_map, 'noofvisitsperyear'),
                'default_technician': self.get_col(
                    col_map, 'defaulttechniciannameoptional', 'defaulttechnician'
                ),
                'contract_type' : self.get_col(col_map,'contracttype'),
            }
    
            created = 0
            errors = []
            seen_serials = set()
    
            # ---------------------------
            # LOOP
            # ---------------------------
            base_dt = fields.Datetime.now()  # call once, before the loop
            for idx, row in df.iterrows():
                row_num = idx + 2
    
                try:
                    # ---------------------------
                    # SERIAL CLEANING (CRITICAL)
                    # ---------------------------
                    serial_no = self.get_val(row, headers, 'serial_no')
                    serial_no = str(serial_no).strip() if serial_no else False
    
                    if serial_no and serial_no.lower() == 'nan':
                        serial_no = False
    
                    # ---------------------------
                    # DUPLICATE CHECK (FILE)
                    # ---------------------------
                    if serial_no:
                        if serial_no in seen_serials:
                            raise UserError(f"Row {row_num}: Duplicate Serial in file: {serial_no}")
                        seen_serials.add(serial_no)
    
                    # ---------------------------
                    # DUPLICATE CHECK (DB)
                    # ---------------------------
                    if serial_no:
                        existing = self.env['maintenance.equipment'].search(
                            [('serial_no', '=', serial_no)], limit=1
                        )
                        if existing:
                            raise UserError(f"Row {row_num}: Duplicate Serial No: {serial_no}")
    
                    # ---------------------------
                    # BASIC FIELDS
                    # ---------------------------
                    asset_tag = self.get_val(row, headers, 'asset_tag')
                    equipment_name = asset_tag or serial_no or "Equipment"
    
                    # ---------------------------
                    # BRAND
                    # ---------------------------
                    brand_id = False
                    brand_name = self.get_val(row, headers, 'brand')
                    if brand_name:
                        brand = self.env['brand'].search([('name', '=', brand_name)], limit=1)
                        if not brand:
                            brand = self.env['brand'].create({'name': brand_name})
                        brand_id = brand.id
    
                    # ---------------------------
                    # MODEL
                    # ---------------------------
                    model_id = False
                    model_code = self.get_val(row, headers, 'model')
                    if model_code and brand_id:
                        model = self.env['equipment.model.code'].search([
                            ('model_code', '=', model_code),
                            ('brand_id', '=', brand_id)
                        ], limit=1)
                        if not model:
                            model = self.env['equipment.model.code'].create({
                                'brand_id': brand_id,
                                'model_code': model_code,
                            })
                        model_id = model.id
    
                    # ---------------------------
                    # PRODUCT (MANDATORY)
                    # ---------------------------
                    unit_type_val = self.get_val(row, headers, 'unit_type')
                    if not unit_type_val:
                        raise UserError(f"Row {row_num}: Unit Type is required")
    
                    # product = self.env['product.product'].search(
                    #     [('name', 'ilike', unit_type_val)], limit=1
                    # )
                    '''Code Added on May 18 2026 by Vijaya Bhaskar'''
                    product = self.env['product.product'].search(
                        [('name', '=', unit_type_val)], limit=1
                    )
                    if not product:
                        raise UserError(f"Row {row_num}: Product not found → '{unit_type_val}'")
    
                    # ---------------------------
                    # TECHNICIAN
                    # ---------------------------
                    technician_id = False
                    tech_name = self.get_val(row, headers, 'default_technician')
    
                    if tech_name:
                        tech_name = tech_name.strip().lower()
                        users = self.env['res.users'].search([])
    
                        for u in users:
                            name = (u.partner_id.name or '').lower()
                            login = (u.login or '').lower()
    
                            if tech_name in name or tech_name in login:
                                technician_id = u.id
                                break
    
                    # ---------------------------
                    # BATCH
                    # ---------------------------
                    batch_no = self.get_val(row, headers, 'batch_no')
                    batch_no = batch_no if batch_no and batch_no.lower() != 'nan' else False
    
                    # ---------------------------
                    # VISITS
                    # ---------------------------
                    visits_val = self.get_val(row, headers, 'no_of_visits_per_year')
                    no_of_visits = int(float(visits_val)) if visits_val else 0
    
                    # ---------------------------
                    # CRM
                    # ---------------------------
                    crm_lead_id = False
                    if self.description:
                        lead = self.env['crm.lead'].search(
                            [('name', 'ilike', self.description.strip())],
                            limit=1
                        )
                        if lead:
                            crm_lead_id = lead.id
                    
                    contract_type = False
                    
                    contract_type = self.get_val(row, headers, 'contract_type')
                    if contract_type:
                        contract_type_search = self.env['crm.contract.type'].search([('name', '=', contract_type)], limit=1)
                        
                        contract_type = contract_type_search.id   
                    
                    # ---------------------------
                    # CREATE
                    # ---------------------------
                    vals = {
                        'name': equipment_name,
                        'serial_no': serial_no or False,  # 🔥 IMPORTANT
                        'brand_id': brand_id,
                        'model_id': model_id,
                        'location': self.get_val(row, headers, 'location') or False,
                        'no_of_visits': no_of_visits,
                        'technician_user_id': technician_id or False,
                        'service_products_code_id': product.id,
                        'service_group_batch': batch_no,
                        'contract_id': self.contract_id.id,
                        'customer': self.customer_id.name,
                        'contract_start_date': self.contract_start_date,
                        'contract_end_date': self.contract_end_date,
                        'description': self.description,
                        'crm_lead_id': crm_lead_id,
                        'maintenance_contract_type_id' :contract_type,
                    }
    
                    # self.env['maintenance.equipment'].create(vals)
                    equipment_create = self.env['maintenance.equipment'].create(vals)
                    fake_create_date = base_dt - datetime.timedelta(microseconds=idx * 1000)
                    self.env.cr.execute(
                        "UPDATE maintenance_equipment SET create_date = %s WHERE id = %s",
                        (fake_create_date, equipment_create.id)
                    )
                    created += 1
    
                except Exception as e:
                    errors.append(str(e))
    
            # ---------------------------
            # RESULT
            # ---------------------------
            message = f"Successfully imported {created} record(s)."
    
            if errors:
                message += f"\n\n{len(errors)} failed:\n" + "\n".join(errors[:10])
    
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('Import Completed'),
                    'message': message,
                    'type': 'success' if created else 'danger',
                    'sticky': True,
                }
            }
    
        except Exception as e:
            raise UserError(f"Failed to read Excel file: {str(e)}")
    
    
    # def action_import_equipment(self):
    #     self.ensure_one()
    #
    #     if not self.file:
    #         raise UserError(_("Please select an Excel file."))
    #
    #     if not pd:
    #         raise UserError(_("pandas is required. Install with: pip install pandas openpyxl"))
    #
    #     try:
    #         file_content = base64.b64decode(self.file)
    #
    #         # ---------------------------
    #         # READ FILE (NO HEADER)
    #         # ---------------------------
    #         df = pd.read_excel(BytesIO(file_content), dtype=str, header=None)
    #         df = df.fillna('')
    #
    #         # ---------------------------
    #         # DETECT HEADER ROW
    #         # ---------------------------
    #         header_row_index = None
    #         for i in range(10):
    #             row_values = df.iloc[i].astype(str).str.lower().tolist()
    #             if any('serial' in val for val in row_values):
    #                 header_row_index = i
    #                 break
    #
    #         if header_row_index is None:
    #             raise UserError("Header row not found. Make sure 'Serial No' column exists.")
    #
    #         df.columns = df.iloc[header_row_index]
    #         df = df[header_row_index + 1:]
    #
    #         # ---------------------------
    #         # COLUMN MAP
    #         # ---------------------------
    #         col_map = {self.normalize(col): col for col in df.columns}
    #         _logger.info(f"Detected columns: {list(col_map.keys())}")
    #
    #         headers = {
    #             'asset_tag': self.get_col(col_map, 'assettagautogenerated', 'assettag'),
    #             'unit_type': self.get_col(col_map, 'unittype'),
    #             'serial_no': self.get_col(col_map, 'serialnooptional', 'serialno'),
    #             'model': self.get_col(col_map, 'model'),
    #             'brand': self.get_col(col_map, 'brand'),
    #             'location': self.get_col(col_map, 'usedinlocationoptional', 'location'),
    #             'batch_no': self.get_col(col_map, 'batchnooptional', 'batchno'),
    #             'no_of_visits_per_year': self.get_col(col_map, 'noofvisitsperyear'),
    #             'default_technician': self.get_col(col_map, 'defaulttechniciannameoptional', 'defaulttechnician'),
    #         }
    #
    #         _logger.info(f"Headers mapping: {headers}")
    #
    #         created = 0
    #         errors = []
    #
    #         # ---------------------------
    #         # LOOP
    #         # ---------------------------
    #         for idx, row in df.iterrows():
    #             row_num = idx + 2
    #             try:
    #                 # SERIAL NO
    #                 serial_no = self.get_val(row, headers, 'serial_no')
    #                 # if not serial_no:
    #                 #     raise UserError(f"Row {row_num}: Serial No is missing")
    #
    #                 # DUPLICATE CHECK
    #                 # if self.env['maintenance.equipment'].search([('serial_no', '=', serial_no)], limit=1):
    #                 #     raise UserError(f"Row {row_num}: Duplicate Serial No: {serial_no}")
    #
    #                 # ASSET TAG
    #                 asset_tag = self.get_val(row, headers, 'asset_tag')
    #                 equipment_name = asset_tag if asset_tag else serial_no
    #
    #                 # BRAND
    #                 brand_name = self.get_val(row, headers, 'brand')
    #                 brand_id = False
    #                 if brand_name:
    #                     brand_rec = self.env['brand'].search([('name', '=', brand_name)], limit=1)
    #                     if not brand_rec:
    #                         brand_rec = self.env['brand'].create({'name': brand_name})
    #                     brand_id = brand_rec.id
    #
    #                 # MODEL
    #                 model_code = self.get_val(row, headers, 'model')
    #                 model_id = False
    #                 if model_code and brand_id:
    #                     model_rec = self.env['equipment.model.code'].search([
    #                         ('model_code', '=', model_code),
    #                         ('brand_id', '=', brand_id)
    #                     ], limit=1)
    #                     if not model_rec:
    #                         model_rec = self.env['equipment.model.code'].create({
    #                             'brand_id': brand_id,
    #                             'model_code': model_code,
    #                         })
    #                     model_id = model_rec.id
    #
    #                 # PRODUCT (MANDATORY)
    #                 unit_type_val = self.get_val(row, headers, 'unit_type')
    #                 if not unit_type_val:
    #                     raise UserError(f"Row {row_num}: Unit Type (Product) is required")
    #
    #                 product = self.env['product.product'].search(
    #                     [('name', 'ilike', unit_type_val)], limit=1
    #                 )
    #                 if not product:
    #                     raise UserError(f"Row {row_num}: Product not found → '{unit_type_val}'")
    #
    #                 product_id = product.id
    #
    #                 # TECHNICIAN
    #                 technician_id = False
    #
    #                 tech_name = self.get_val(row, headers, 'default_technician_name_optional')
    #
    #                 if tech_name:
    #                     import re
    #                     tech_name = re.sub(r'\s+', ' ', tech_name).strip().lower()
    #
    #                     print("SEARCHING FOR:", tech_name)
    #
    #                     users = self.env['res.users'].search([])
    #
    #                     matched_user = False
    #
    #                     for u in users:
    #                         name = (u.partner_id.name or '').lower()
    #                         login = (u.login or '').lower()
    #
    #                         if tech_name in name or tech_name in login:
    #                             matched_user = u
    #                             print("MATCH FOUND:", name, login)
    #                             break
    #
    #                     if matched_user:
    #                         technician_id = matched_user.id
    #                         print("FOUND ID:", technician_id)
    #                     else:
    #                         _logger.warning("Technician NOT found: '%s'", tech_name)
    #
    #                 # BATCH NO ✅ FIXED
    #                 batch_no = self.get_val(row, headers, 'batch_no')
    #                 batch_no = batch_no if batch_no and batch_no.lower() != 'nan' else False
    #
    #                 _logger.info(f"Row {row_num} Batch No: {batch_no}")
    #
    #                 # VISITS
    #                 visits_val = self.get_val(row, headers, 'no_of_visits_per_year')
    #                 no_of_visits = int(float(visits_val)) if visits_val else 0
    #
    #                 crm_lead_id = False
    #
    #                 if self.description:
    #                     lead = self.env['crm.lead'].search([
    #                         ('name', 'ilike', self.description.strip())
    #                     ], limit=1)
    #
    #                     if lead:
    #                         crm_lead_id = lead.id
    #                     else:
    #                         raise UserError(
    #                             f"CRM Lead not found for description: '{self.description}'"
    #                         )
    #
    #                 # CREATE
    #                 vals = {
    #                     'name': equipment_name,
    #                     'serial_no': serial_no,
    #                     'brand_id': brand_id,
    #                     'model_id': model_id,
    #                     'location': self.get_val(row, headers, 'location') or False,
    #                     'no_of_visits': no_of_visits,
    #                     'technician_user_id': technician_id or False,
    #                     'service_products_code_id': product_id,
    #                     'service_group_batch': batch_no,
    #                     'contract_id': self.contract_id.id,
    #                     'customer': self.customer_id.name,
    #                     'contract_start_date': self.contract_start_date,
    #                     'contract_end_date': self.contract_end_date,
    #                     'description': self.description,
    #                     'crm_lead_id': crm_lead_id,
    #                 }
    #
    #                 self.env['maintenance.equipment'].create(vals)
    #                 created += 1
    #
    #             except Exception as e:
    #                 errors.append(str(e))
    #                 _logger.exception("Import error at row %s", row_num)
    #
    #         # ---------------------------
    #         # RESULT MESSAGE
    #         # ---------------------------
    #         message = f"Successfully imported {created} equipment record(s)."
    #
    #         if errors:
    #             message += f"\n\n{len(errors)} row(s) failed:\n" + "\n".join(errors[:10])
    #
    #         return {
    #             'type': 'ir.actions.client',
    #             'tag': 'display_notification',
    #             'params': {
    #                 'title': _('Import Completed'),
    #                 'message': message,
    #                 'type': 'success' if created else 'danger',
    #                 'sticky': True,
    #             }
    #         }
    #
    #     except Exception as e:
    #         raise UserError(f"Failed to read Excel file: {str(e)}")
