{
    'name': 'Regular table to API Module',
    'version': '1.1',
    'depends': ['base', 'project'],
    'author':'Ramesh Manivannan',
    'data': [
        'security/ir.model.access.csv',
        'views/bisalary_views.xml',        
        'views/catalog_views.xml',
        'views/catalogdesc_views.xml',
        'views/customer_views.xml',
        'views/customerdesc_views.xml',
        'views/customergroups_views.xml',
        'views/sl_salesmandesc_views.xml',
        # 'views/stock_quant_views.xml',
        'views/t_cstclassification_views.xml',
        'views/t_cstclassificationdesc_views.xml',
        'views/t_cstclasstypedesc_views.xml',
        'views/t_cstgroupdesc_views.xml',
        'views/t_groupsdesc_views.xml',
        'views/t_productsdesc_views.xml',
        'views/t_productsubs_views.xml',
        'views/t_productsubsdesc_views.xml',
        'views/t_productsubsdescgroup_views.xml',
        'views/t_regionsdesc_views.xml',
        'views/t_subregions_views.xml',
        'views/t_subregionsdesc_views.xml',
        'views/t_warehouse_views.xml',
        'views/t_warehousedesc_views.xml',
        'views/db_project_task_view.xml'

    ],
    'installable': True,
    'application': True,
}