#!/usr/bin/env python3
"""Snapshot the *current live* chart layout (order / position / size) of the
Service Dashboards boards (menu 1222) back into BOTH module data files:

  * service_dashboards_ot/data/service_dashboard_layout.xml   (legacy boards module)
        -> grid_corners per legacy_/board_ item, keyed by xmlid, Python-dict
           format, plus the <function> gridstack-rebuild call.
  * service_dashboards_ct/views/service_dashboards_data.xml  (menu-shell module)
        -> grid_corners on each sd_item_<id> record updated in place (JSON,
           &quot;-escaped). sd_item_<NNN> maps to live item id <NNN>.

The Custom Theme boards (menu 1100) are intentionally NOT written: their layout
is derived from these source boards by the copy-migration, and currently matches.

Positions are taken from each board's ks_gridstack_config (the authoritative
render source), exported beforehand to:
    /tmp/sd_boards_1222.json   (board_id, board_name, gridstack, board_xmlid)
    /tmp/sd_items_1222.json    (item_id, board_id, item_xmlid)

Run on the host (writes directly to the iCloud repo files):
    python3 scripts/save_service_dashboard_layouts.py
"""

import json
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LAYOUT_XML = os.path.join(REPO, "service_dashboards_ot/data/service_dashboard_layout.xml")
PLURAL_XML = os.path.join(REPO, "service_dashboards_ct/views/service_dashboards_data.xml")

# Section ordering for the singular layout file (same as dump_service_dashboards.py).
LEGACY_BOARD_ORDER = [
    "legacy_board_uwc", "legacy_board_c", "legacy_board_e", "legacy_board_w",
    "legacy_board_jcs", "legacy_board_cc", "legacy_board_crd",
    "legacy_board_sales_cost", "legacy_board_main", "legacy_board_parts",
    "legacy_board_technician",
]
USER_BOARD_ORDER = [
    "board_service_analysis_cc_users", "board_service_analysis_crd_users",
    "board_service_analysis_parts_users", "board_service_analysis_technicians",
]


def _load():
    boards = json.load(open("/tmp/sd_boards_1222.json"))
    items = json.load(open("/tmp/sd_items_1222.json"))
    board_xmlid = {}        # board_id -> short xmlid
    board_gridstack = {}    # board_id -> {str(item_id): {x,y,w,h}}
    for b in boards:
        board_xmlid[b["board_id"]] = b["board_xmlid"]
        board_gridstack[b["board_id"]] = json.loads(b["gridstack"]) if b["gridstack"] else {}
    item_pos = {}           # item_id -> {x,y,w,h}
    item_xmlid = {}         # item_id -> short xmlid (or None)
    items_by_board = {}     # board_xmlid -> [item_id, ...] ordered by id
    for it in items:
        iid = it["item_id"]
        bid = it["board_id"]
        gs = board_gridstack.get(bid, {})
        pos = gs.get(str(iid))
        if pos is not None:
            item_pos[iid] = {k: int(pos[k]) for k in ("x", "y", "w", "h")}
        item_xmlid[iid] = it["item_xmlid"]
        items_by_board.setdefault(board_xmlid[bid], []).append(iid)
    for bx in items_by_board:
        items_by_board[bx].sort()
    return item_pos, item_xmlid, items_by_board


def _py_pos(p):
    return "{'x': %d, 'y': %d, 'w': %d, 'h': %d}" % (p["x"], p["y"], p["w"], p["h"])


def _json_pos(p):
    return ('{&quot;x&quot;: %d, &quot;y&quot;: %d, &quot;w&quot;: %d, &quot;h&quot;: %d}'
            % (p["x"], p["y"], p["w"], p["h"]))


def write_layout_file(item_pos, item_xmlid, items_by_board):
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<odoo>",
        '    <data noupdate="0">',
        "",
        "        <!-- Chart positions for every service_dashboard board.",
        '             noupdate="0" so positions re-apply on every -u service_dashboard;',
        "             the trailing <function/> call rebuilds the per-board",
        "             ks_gridstack_config so the UI actually renders in the",
        "             refreshed order. Regenerated by scripts/save_service_dashboard_layouts.py.",
        "          -->",
        "",
    ]
    n = 0
    for order in (LEGACY_BOARD_ORDER, USER_BOARD_ORDER):
        for bx in order:
            for iid in items_by_board.get(bx, []):
                pos = item_pos.get(iid)
                xid = item_xmlid.get(iid)
                if pos is None or not xid:
                    continue
                out.append('        <record id="%s" model="ks_dashboard_ninja.item">' % xid)
                out.append('            <field name="grid_corners">%s</field>' % _py_pos(pos))
                out.append("        </record>")
                n += 1
    out += [
        "",
        "        <!-- Refresh per-board gridstack_config from the grid_corners just",
        "             written above. Without this, the UI keeps rendering the old",
        "             layout even though the underlying positions changed. -->",
        '        <function model="ks_dashboard_ninja.board"'
        ' name="service_dashboard_rebuild_layouts"/>',
        "",
        "    </data>",
        "</odoo>",
        "",
    ]
    with open(LAYOUT_XML, "w") as f:
        f.write("\n".join(out))
    print("Wrote %s (%d items)" % (LAYOUT_XML, n))


def patch_plural_file(item_pos):
    text = open(PLURAL_XML).read()
    # Split into per-record blocks for sd_item_<id>, replace/insert grid_corners.
    rec_re = re.compile(
        r'(<record id="sd_item_(\d+)" model="ks_dashboard_ninja\.item">)(.*?)(</record>)',
        re.S,
    )
    gc_re = re.compile(r'([ \t]*)<field name="grid_corners">.*?</field>\n')
    board_re = re.compile(r'(<field name="ks_dashboard_ninja_board_id"[^>]*/>\n)')

    updated = {"set": 0, "inserted": 0, "skipped": 0}

    def repl(m):
        head, nnn, body, tail = m.group(1), int(m.group(2)), m.group(3), m.group(4)
        pos = item_pos.get(nnn)
        if pos is None:
            updated["skipped"] += 1
            return m.group(0)
        new_field = '<field name="grid_corners">%s</field>' % _json_pos(pos)
        if gc_re.search(body):
            body = gc_re.sub(
                lambda gm: '%s%s\n' % (gm.group(1), new_field), body, count=1)
            updated["set"] += 1
        else:
            # Insert right after the board_id field, matching the record's
            # 12-space field indentation.
            bm = board_re.search(body)
            if bm:
                insert = '            %s\n' % new_field
                body = body[:bm.end()] + insert + body[bm.end():]
                updated["inserted"] += 1
            else:
                updated["skipped"] += 1
        return head + body + tail

    new_text = rec_re.sub(repl, text)
    with open(PLURAL_XML, "w") as f:
        f.write(new_text)
    print("Patched %s (set=%d inserted=%d skipped=%d)"
          % (PLURAL_XML, updated["set"], updated["inserted"], updated["skipped"]))


def main():
    item_pos, item_xmlid, items_by_board = _load()
    write_layout_file(item_pos, item_xmlid, items_by_board)
    patch_plural_file(item_pos)


if __name__ == "__main__":
    main()
