{
    "name": "Service Dashboards",
    "version": "17.0.1.0.0",
    "category": "Services",
    "summary": "Service Dashboards menu",
    "author": "Your Company",
    "website": "https://www.yourcompany.com",
    "depends": ["ks_dashboard_ninja"],
    "data": [
        "views/service_dashboards_menus.xml",
        # views/service_dashboards_data.xml is intentionally NOT loaded.
        # The 15 "Service Dashboards" boards under this module's menu_root are
        # owned and maintained by the `service_dashboard` module (legacy_/board_
        # records). Loading this file would CREATE 15 duplicate boards under the
        # same menu. It is kept on disk purely as a faithful layout/position
        # snapshot (sd_board_*/sd_item_*), regenerated by
        # scripts/save_service_dashboard_layouts.py.
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
    "license": "LGPL-3",
}
